### ISSUE TITLE
Eerste feedbackronde - Bas

### ISSUE THREAD

**Issue by baskraai** [baskraai/computerarch-paper-uu#1]

**Comment by baskraai** [comment]
- [ ] Veranderd namen Albert en Bert -> Alice en Bob

**Comment by BramLankhorst** [comment]
Misschien niet heel belangrijk voor nu maar kwam wat spelfouten tegen: 
-[ ] "Bert _start_ with computing the session key by using _it_ private key" 
- [ ] "In RSA this are two seperate _transmission_  because of the lack of public-private key pair on the side of the sender (Albert)."
- [ ] "This also makes both schemas _heavly dependand_ on the Diﬃe-Hellman problem what is at the moment only eﬃciently _solvale_ with the _dicrete logarith_ problem. "

**Comment by rjanssen96** [comment]
- [ ] RDA -> RSA in de eerste alinea pagina 9
- [ ] 4.1: In the graphic below, even netjes verwijzen
- [ ] Verander safe prime number in random large prime number
- [ ] Wellicht een genummerde opsomming gebruiken voor de stappen  van Elgamal
- [ ] Ik mis de bronvermeldingen
- [ ] Sectie 4.2 mag korter of weg als we teveel worden hebben.
- [ ] Check even in alle secties de "an" en  "a". Je gebruikt vaak an ipv a.
- [ ] Wiskunde in Latex verwerken. Zodat a^x netjes verwerkt wordt

**Comment by HerbermannMax98** [comment]
- [ ] 'Encryptionscheme' --> 'Encryption scheme'. twee keer verbeteren in de inleiding van Elgamal.
- [ ] Let een paar keer goed op of je 'send' gebruikt, of 'sent'. "Needs to be sent" moet namenlijk met een t ipv een d.

De rest van mijn feedback is al aan bod gebracht door de rest.
